Rails.application.routes.draw do
  get 'homepage/index'
  root 'homepage#index'
  get 'doctor/index', to: 'doctor#index'

#  get 'appointment/index' 
#  get 'appointment/show'
#  get 'appointment/new'
#  get 'appointment/edit'
#  get 'appointment/create'
#  get 'appointment/update'
#  get 'appointment/destroy'
#  get 'specialization/index'
#  get 'specialization/show'
#  get 'specialization/new'
#  get 'specialization/edit'
#  get 'specialization/create'
#  get 'specialization/update'
#  get 'specialization/destroy'
#  get 'patient/index'
#  get 'patient/show'
#  get 'patient/new'
#  get 'patient/edit'
#  get 'patient/create'
#  get 'patient/update'
#  get 'patient/destroy'
#  get 'doctor/show'
#  get 'doctor/new'
#  get 'doctor/edit'
#  get 'doctor/create'
#  get 'doctor/update'
#  get 'doctor/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end
