Rails.application.routes.draw do
  get 'homepage/index'
  root 'homepage#index'
  get 'doctors/main', to: 'doctors#main'
  resources :doctors
#  get 'appointments/index' 
#  get 'appointments/show'
#  get 'appointments/new'
#  get 'appointments/edit'
#  get 'appointments/create'
#  get 'appointments/update'
#  get 'appointments/destroy'
#  get 'specializations/index'
#  get 'specializations/show'
#  get 'specializations/new'
#  get 'specializations/edit'
#  get 'specializations/create'
#  get 'specializations/update'
#  get 'specializations/destroy'
#  get 'patients/index'
#  get 'patients/show'
#  get 'patients/new'
#  get 'patients/edit'
#  get 'patients/create'
#  get 'patients/update'
#  get 'patients/destroy'
  get 'doctors/new', to: 'doctors#new'
  get 'doctors/:id', to: 'doctors#show'
  get 'doctors', to: 'doctors#index' 
  get 'doctors/:id/edit', to: 'doctors#edit'
  post 'doctors', to: 'doctors#create'
#  get 'doctors/update'
#  get 'doctors/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end
