# This file overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: 'Your_Gmail_Username'
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
GMAIL_USERNAME: 'madhurimachhabra@gmail.com'
GMAIL_PASSWORD: ''
GOOGLE_CLIENT_ID: '200919102635-1vimkviek3iidc9240j405020qmfb9mc.apps.googleusercontent.com'
GOOGLE_SECRET: 'U2dRWTdWBiTwqYNRtVYGGg-r'